### PR TITLE
Update to prettier 3.0

### PR DESCRIPTION
**Pull request by Nerixyz**
This PR updates `prettier` to 3.0.

[Changelog](https://prettier.io/blog/2023/07/05/3.0.0.html)

### CODE REVIEW

**Comment by dylanvorster** [comment]
works for me :P https://github.com/projectstorm/react-workspaces/pull/52 :shipit:

**Comment by Nerixyz** [comment]
Forgot to rebuild after I added the comment. Should have the correct output now.

**Comment by Nerixyz** [comment]
Can't replicate the CI failure on my machine. Maybe it's something related to line-endings?

**Comment by Nerixyz** [comment]
Seems like `@vercel/ncc` was outdated.

**Comment by phuctm97** [comment]
Maybe switch to Node 18?

**Comment by Nerixyz** [comment]
OK, fingers crossed, this should finally work. I tested it in https://github.com/Nerixyz/dwd-api-rs/pull/1, and it doesn't seem to contain absolute paths. I can squash the commits if desired.

**Comment by Nerixyz** [comment]
Guess I forgot to clean the folder before 🤦 For some reason, I can't get this to compile the same on Windows vs. Linux. On Windows, `ncc` outputs code that uses `require` while on Linux it correctly uses `createRequrire`. Not sure if that's an `ncc` bug.

**Comment by phuctm97** [comment]
Just released it to `v3` now, thank you @Nerixyz!

**Pull request merged**
